### ISSUE TITLE
Can't download artifacts from S3

### ISSUE THREAD

**Issue by emaks** [awslabs/aws-codebuild-jenkins-plugin#111]
I have buildspec.yml
```
version: 0.2

phases:
  install:
    commands:
      -  #some commands
  build:
    commands:
      -  #some commands
    finally:
      - zip -qr output.zip build/results/*
artifacts:
  files: output.zip
  base-directory: <project-folder>
```

and in Jenkinsfile configuration for run CodeBuild
```
stage('Execute CodeBuild') {
    steps {
        script {
            envVariables = "[{ENV,${params.env}},{REGION,${getRegion()}}]"
        }
        withAWS(region: params.region, role: role, roleAccount: params.sdlcAccount) {
            awsCodeBuild(
                credentialsType: 'keys',
                projectName: "${codebuildProject}",
                region: "${params.region}",
                sourceControlType: 'jenkins',
                sourceTypeOverride: 'S3',
                sourceLocationOverride: "${s3Bucket}/artifacts/${JOB_BASE_NAME}-${BUILD_ID}/source.zip",
                buildSpecFile: '.jenkins/buildspec.yml',
                envVariables: "${envVariables}",
                artifactTypeOverride: 'S3',
                artifactLocationOverride: "${s3Bucket}",
                artifactPathOverride: 'artifacts',
                artifactNameOverride: "${JOB_BASE_NAME}-${BUILD_ID}",
                downloadArtifacts: 'true'
            )
        }
    }
}

```

When I execute jenkins job I get error 
```
[AWS CodeBuild Plugin] Downloading artifact from location 'arn:aws:s3:::${s3Bucket}/artifacts/${JOB_BASE_NAME}-${BUILD_ID}' to path:/home/jenkins/workspace/<jenkins-project>/.
[AWS CodeBuild Plugin] Couldn't create parent directories for /home/jenkins/workspace/<jenkins-project>/artifacts/${JOB_BASE_NAME}-${BUILD_ID}/output.zip
```

If I remove ```downloadArtifacts: 'true' ``` and add separate step
```
s3Download(bucket: "${s3Bucket}", path: "artifacts/${JOB_BASE_NAME}-${BUILD_ID}/output.zip", file: 'output.zip')
```
everything work fine
